### PR TITLE
Implementing cache expiration check

### PR DESCRIPTION
**Pull request by volponi**
There was no way to effectively expire a cached file. This commit adds a check on the cachetime parameter of the file. If the cache has expired (and is not infinite), the file must be deleted and a new version must be retrieved to be cached again.

Related issue: #4

### CODE REVIEW

**Comment by dereuromark** [comment]
I wonder if we can avoid the 2x 

```
$content = file_get_contents($file);
```

now and once read store it in a protected variable to be reused?
The file reading is usually the slowest operation here.

**Comment by jorisvaesen** [comment]
If you write the cache expiration time on the first line and the html from the next line, you can use `$time = fgets(fopen($file, 'r'));` to read the first line only so there is no overhead.

**Comment by dereuromark** [comment]
Well, then I dont have any further objections.

**Comment by jorisvaesen** [comment]
I pointed this out as an option, this is not in the PR so it shouldn't get merged yet?

**Comment by dereuromark** [comment]
Oh please make a new PR

**Pull request merged**
